name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - run: pip install --upgrade pip
      - run: pip install -e '.[dev]'

      - run: ruff check .

      - run: pytest -q

      # build wheel to ensure packaging works
      - run: |
          python -m pip install build
          python -m build --wheel --no-isolation
